import store from '../store'

const locales = {
	'ru-RU': {
		ProfileTitle: 'Профиль',
		NameInput: 'Имя',
		Reload: 'Обновить',
		Categories: 'Категории',
		NoCategories: 'Категорий пока нет',
		AddNewCategory: 'Добавить новую категорию',
		CategoryCreated: 'Успешно добавлена новая категория',
		NoRecordOnId_1: 'Запись с id ',
		NoRecordOnId_2: ' не найдена',
		History: 'История',
		Description: 'Описание: ',
		Sum: 'Сумма:',
		Category: 'Категория',
		NoRecords: 'Записей пока нет.',
		AddNewRecord: 'Добавить новую запись',
		Bill: 'Счет',
		NewRecord: 'Новая запись',
		CategoryChoose: 'Выберите категорию',
		Income: 'Доход',
		Outcome: 'Расход',
		Create: 'Создать',
		DescriptionRequired: 'Необходимо описание',
		MinValue: 'Минимальное значение',
		RecordCreated: 'Запись успешно создана',
		NotEnoughMoney: 'Недостаточно средств на счете',
		PasswordLength: 'Пароль должен быть как минимум',
		Symbols: 'символов',
		CurrentPasswordLength: 'Сейчас он',
		HomeAccounting: 'Домашняя бугалтерия',
		SignUp: 'Зарегистрироваться',
		RulesAgree: 'С правилами согласен',
		AccountAlready: 'Уже есть аккаунт?',
		Excess: 'Превышение на',
		LeftOver: 'Осталось',
		LogOut: 'Выйти',
		Planning: 'Планирование',
		From: 'из',
		Profile: 'Профиль',
		Limit: 'Лимит',
		Title: 'Название',
		EnterCategoryName: 'Введите название категории',
		Edit: 'Изменить',
		Delete: 'Удалить',
		CategoryUpdate: 'Категория обновлена',
		CategoryRemove: 'Категория удалена',
		CheckRecord: 'Посмотреть запись',
		Date: 'Дата',
		Type: 'Тип',
		Open: 'Открыть',
		ExchangeRates: 'Курс валют',
		Currency: 'Валюта',
		ExchangeRate: 'Курс валюты'
	},
	'en-US': {
		ProfileTitle: 'Profile',
		NameInput: 'Name',
		Reload: 'Reload',
		Categories: 'Categories',
		NoCategories: 'No categories yet',
		AddNewCategory: 'Add new category',
		CategoryCreated: 'New category has been created',
		NoRecordOnId_1: 'Record with id ',
		NoRecordOnId_2: ' wasn\'t found',
		History: 'History',
		Description: 'Description: ',
		Sum: 'Summary: ',
		Category: 'Category: ',
		NoRecords: 'No records yet.',
		AddNewRecord: 'Add new record',
		Bill: 'Bill',
		NewRecord: 'New record',
		CategoryChoose: 'Choose a category',
		Income: 'Income',
		Outcome: 'Outcome',
		Create: 'Create',
		DescriptionRequired: 'The description is required',
		MinValue: 'Minimal value is',
		RecordCreated: 'Record has been created successfully',
		NotEnoughMoney: 'Not enough money',
		PasswordLength: 'Password must be at least',
		Symbols: 'symbols',
		CurrentPasswordLength: 'Now it\'s',
		HomeAccounting: 'Home accounting',
		SignUp: 'Sign up',
		RulesAgree: 'I agree with rules',
		AccountAlready: 'Already have an account?',
		Excess: 'Excess on',
		LeftOver: 'Left over',
		LogOut: 'Log out',
		Planning: 'Planning',
		From: 'from',
		Profile: 'Profile',
		Limit: 'Limit',
		Title: 'Title',
		EnterCategoryName: 'Enter category name',
		Edit: 'Edit',
		Delete: 'Delete',
		CategoryUpdate: 'Category has been updated',
		CategoryRemove: 'Category has been removed',
		CheckRecord: 'Check the record',
		Date: 'Date',
		Type: 'Type',
		Open: 'Open',
		ExchangeRates: 'ExchangeRates',
		Currency: 'Currency',
		ExchangeRate: 'Exchange rate'
	},
};

export default (key) => {
	const locale = store.getters.info.locale || 'en-US'
	return locales[locale][key] || `[Localize error]: key ${key} not found`
}